export enum Commands {
  PING = 'ping',
  BAN = 'ban',
  MSG_TOP = 'msgTop',
  MSG_RANK = 'msgRank',
  MUTE = 'mute',
  UNMUTE = 'unmute',
  HELP = 'help',
  MIMIC = 'mimic',
  UNMIMIC = 'unmimic',
  TAG_ALL = 'tagAll',
  PURGE = 'purge',
  TOTAL_MSG_RANK = 'totalMsgRank',
  TOTAL_MSG_TOP = 'totalMsgTop',
};