name: Deploy to Google App Engine

on:
  push:
    branches:
      - master


jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCLOUD_KEY }}
      
      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS

      - name: Install dependencies
        run: npm ci
        working-directory: packages/main-be

      - name: Build application
        run: npm run build
        working-directory: packages/main-be

      - name: Deploy to Google App Engine
        run: gcloud app deploy --quiet
        working-directory: packages/main-be
      