name: Deploy to Google App Engine

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCLOUD_KEY }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          service_account_key: ${{ secrets.GCLOUD_KEY }}

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: packages/main-be

      # Step 5: Build application
      - name: Build application
        run: npm run build
        working-directory: packages/main-be

      # Step 6: Deploy to Google App Engine with environment variables
      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy --quiet --project=${{ secrets.GCLOUD_PROJECT }} \
            --update-env-vars "$(echo "${{ secrets.ENV_PROD_FILE }}" | tr '\n' ',' | sed 's/,$//')"
        working-directory: packages/main-be
